import type { SupabaseClient } from '@supabase/supabase-js'

/**
 * CONTENT PROVENANCE — the one write path, and the disclosure it supports.
 *
 * `asset_provenance` existed from migration 0001 with zero code references and
 * zero rows. `S-S` §2.1 called Content Credentials parity "an engine away"; this
 * is the engine, and 0064 is its schema.
 *
 * ── THE STANDARD, AND WHAT WE TOOK FROM IT ─────────────────────────────────
 *
 * C2PA (spec 2.4) models provenance as SIGNED ACTIONS on an asset, not as a
 * flag. The vocabulary below is theirs verbatim — `c2pa.created`, `c2pa.placed`,
 * and the IPTC `digitalsourcetype` URLs — so that the day a generation pipeline
 * produces real media, emitting a genuine manifest is a serialization step
 * rather than a migration.
 *
 * The CAI's SDKs (`c2pa-rs`, `c2pa-js`, both MIT/Apache-2.0) are deliberately
 * NOT a dependency: they embed manifests into binary assets, and every AI call
 * this product makes today produces TEXT into a `documents` row. There is
 * nothing to sign yet. 0064's header carries the full reasoning.
 *
 * ── THE MOMENT THAT MATTERS IS THE APPLY, NOT THE GENERATION ───────────────
 *
 * This is the design decision the whole file turns on. A model producing a
 * paragraph the writer reads and discards is not provenance — it is a draft
 * nobody kept. A paragraph the writer INSERTS into the screenplay is a fact
 * about the screenplay, and it is the only one a studio can be asked to declare.
 *
 * So nothing is recorded when the assistant answers. A row is written when its
 * output is accepted into an artifact, which is `onApply` in the assistant and
 * nowhere else. That makes the table small, true, and about the document rather
 * than about the chat.
 *
 * ── ON THE USER CLIENT, ALWAYS ─────────────────────────────────────────────
 *
 * Every function takes `db` so the caller hands it the cookie-bound client
 * (AD-001). 0064's policy is the boundary: org match, membership, and the
 * project scope of the document or file the row is about. A service-role write
 * here would record provenance against a document the writer cannot see, which
 * is the one thing a provenance record must never do.
 */

/** IPTC digitalsourcetype terms. The constraint in 0064 holds the namespace. */
export const IPTC_SOURCE = {
  /** Wholly generated by a model. */
  trainedAlgorithmicMedia:
    'http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia',
  /** Generated content combined with human work — the normal case in a script. */
  composite:
    'http://cv.iptc.org/newscodes/digitalsourcetype/compositeWithTrainedAlgorithmicMedia',
  /** A camera or recording device. */
  digitalCapture:
    'http://cv.iptc.org/newscodes/digitalsourcetype/digitalCapture',
  /** A person, unaided. */
  humanEdits:
    'http://cv.iptc.org/newscodes/digitalsourcetype/humanEdits',
} as const

export type IptcSource = (typeof IPTC_SOURCE)[keyof typeof IPTC_SOURCE]

/** C2PA `c2pa.actions.v2` action names, as constrained by 0064. */
export type ProvenanceAction = 'c2pa.created' | 'c2pa.edited' | 'c2pa.placed' | 'c2pa.opened'

/** CAWG `cawg.training-mining` permission values. */
export type TrainingPermission = 'allowed' | 'notAllowed' | 'constrained'

export type ProvenanceRow = {
  id: string
  organization_id: string
  document_id: string | null
  file_id: string | null
  parent_asset_id: string | null
  action: ProvenanceAction
  digital_source_type: string | null
  model: string | null
  prompt: string | null
  seed: string | null
  params: Record<string, unknown>
  chars: number | null
  created_by: string | null
  created_at: string
}

const COLUMNS =
  'id, organization_id, document_id, file_id, parent_asset_id, action, digital_source_type, model, prompt, seed, params, chars, created_by, created_at'

/**
 * A prompt is evidence, so it is stored — but it is also unbounded user text
 * arriving on every apply. Truncated rather than rejected: a clipped prompt
 * still answers "what was asked for", and refusing the write would lose the
 * disclosure entirely to protect a column.
 */
export const PROMPT_CAP = 2000

export type RecordGenerationParams = {
  organizationId: string
  /** Exactly one subject. 0064's CHECK enforces at least one; the caller's
   *  intent should be exactly one, and passing both is a bug not a feature. */
  documentId?: string | null
  fileId?: string | null
  /** The model id from `lib/ai/models` — C2PA's `softwareAgent`. */
  model: string
  prompt?: string | null
  seed?: string | null
  params?: Record<string, unknown>
  /** How much generated content actually entered the subject. */
  chars: number
  action: ProvenanceAction
  digitalSourceType?: IptcSource
  /** C2PA's ingredient chain: the asset this one was derived from. */
  parentAssetId?: string | null
  createdBy: string
}

export async function recordGeneration(
  db: SupabaseClient,
  p: RecordGenerationParams
): Promise<ProvenanceRow | null> {
  if (!p.documentId && !p.fileId) {
    throw new Error('recordGeneration: a provenance row must name a document or a file')
  }

  const { data, error } = await db
    .from('asset_provenance')
    .insert({
      organization_id: p.organizationId,
      document_id: p.documentId ?? null,
      file_id: p.fileId ?? null,
      parent_asset_id: p.parentAssetId ?? null,
      action: p.action,
      // A script is human work with generated passages placed into it, so the
      // composite term is the honest default — `trainedAlgorithmicMedia` would
      // claim the whole document came from a model.
      digital_source_type: p.digitalSourceType ?? IPTC_SOURCE.composite,
      model: p.model,
      prompt: p.prompt ? p.prompt.slice(0, PROMPT_CAP) : null,
      seed: p.seed ?? null,
      params: p.params ?? {},
      chars: p.chars,
      created_by: p.createdBy,
    })
    .select(COLUMNS)
    .maybeSingle()

  // RLS refuses by matching zero rows and PostgREST returns no error
  // (HANDOFF §12 lesson 6), so an absent row is a refusal, not a success.
  if (error) throw new Error(`recordGeneration: ${error.message}`)
  return (data as unknown as ProvenanceRow) ?? null
}

/** Every generated passage in one document, oldest first. */
export async function readDocumentProvenance(
  db: SupabaseClient,
  documentId: string,
  limit = 500
): Promise<ProvenanceRow[]> {
  const { data, error } = await db
    .from('asset_provenance')
    .select(COLUMNS)
    .eq('document_id', documentId)
    .order('created_at', { ascending: true })
    .limit(limit)
  if (error) throw new Error(`readDocumentProvenance: ${error.message}`)
  return (data ?? []) as unknown as ProvenanceRow[]
}

// ── the disclosure ──────────────────────────────────────────────────────────

export type Disclosure = {
  /** Number of accepted generations. */
  passages: number
  /** Characters that entered the document from a model. */
  generatedChars: number
  /** 0–1, or null when the document's own length is unknown. */
  share: number | null
  /** Distinct models, most-used first. */
  models: { model: string; passages: number; chars: number }[]
  /** The one sentence a studio can put in front of a union or a broadcaster. */
  statement: string
}

/**
 * What a studio actually has to declare, in one sentence.
 *
 * PROPORTION, NOT PRESENCE. "This document contains AI content" is true of a
 * script where a model fixed one line and of one where a model wrote every
 * scene, and those are not the same disclosure. WGA and broadcaster AI terms
 * turn on how much and which parts, so the share is the number that matters and
 * a boolean would be the wrong answer shaped like the right one.
 *
 * `docChars` is the CURRENT length of the document. The share is therefore an
 * upper bound that decays honestly: generated text the writer later rewrote
 * still counts as having entered, which errs toward over-disclosure. Erring the
 * other way would let a studio edit its way out of a declaration.
 */
export function disclosure(rows: ProvenanceRow[], docChars: number | null): Disclosure {
  const generatedChars = rows.reduce((n, r) => n + (r.chars ?? 0), 0)

  const byModel = new Map<string, { passages: number; chars: number }>()
  for (const r of rows) {
    const key = r.model ?? 'unknown model'
    const cur = byModel.get(key) ?? { passages: 0, chars: 0 }
    cur.passages += 1
    cur.chars += r.chars ?? 0
    byModel.set(key, cur)
  }
  const models = [...byModel.entries()]
    .map(([model, v]) => ({ model, ...v }))
    .sort((a, b) => b.chars - a.chars)

  const share =
    docChars && docChars > 0 ? Math.min(1, generatedChars / docChars) : null

  let statement: string
  if (rows.length === 0) {
    statement = 'No AI-generated content has been accepted into this document.'
  } else {
    const pct = share == null ? null : Math.round(share * 100)
    const who = models.length === 1 ? models[0].model : `${models.length} models`
    statement =
      pct == null
        ? `${rows.length} passage${rows.length === 1 ? '' : 's'} from ${who} ${rows.length === 1 ? 'was' : 'were'} accepted into this document.`
        : `${pct}% of this document — ${rows.length} passage${rows.length === 1 ? '' : 's'} — came from ${who}.`
  }

  return { passages: rows.length, generatedChars, share, models, statement }
}
